name: Python PyPI Builder and Publisher

on:
  release:
    types: [published]

jobs:
  build-publish:
    name: Builds and publishes a Python-based distribution to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checks the Branch
        uses: actions/checkout@v4
      - name: Sets the Environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Installs pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Builds the Wheel
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Publishes to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
